### PR TITLE
fix(issues): restore list filters and search subcommand

### LINKED ISSUE #121: issues list missing filter flags (--team, --project, --status, --assignee) after search merger
## Summary

v2026.4.1 CHANGELOG states: "`search` subcommands merged into `list` — use `issues list --status ...` instead of `issues search --status ...`"

The README also shows filtered usage: `linearis issues list --query "authentication" --team Platform`

But the installed v2026.4.2 binary and source on `main` do not implement these filters on `issues list`.

## Repro

```bash
npm install -g linearis@2026.4.2
linearis issues list --help
# Only shows: --query, --limit, --after
# No --team, --project, --status, --assignee

linearis issues list --team CC -l 1
# error: unknown option '--team'
```

## Source confirmation

`src/commands/issues.ts` on `main`:
- `ListOptions` interface has only `query`, `limit`, `after`
- `issues list` command defines only `--query`, `--limit`, `--after`
- No `--team`, `--project`, `--status`, or `--assignee` options

## Additional breaking change: output shape

`issues list` returns `{ nodes: [...], pageInfo: {...} }` instead of the flat array that `issues search` returned in v2025.12.3. This breaks downstream JSON consumers even for unfiltered queries.

## Impact

Any automation that used `issues search` with filter flags has no CLI equivalent in v2026.4.x. The only workarounds are:
- Stay on v2025.12.3
- Use raw GraphQL queries instead of the CLI

## Expected behavior

`issues list` should support the same filter flags that `issues search` had, as documented in the CHANGELOG and README:
- `--team <team>`
- `--project <project>`
- `--status <status>` (comma-separated)
- `--assignee <user>`

## Environment

- linearis v2026.4.2 (npm)
- macOS 15.4 / Node v24.14.0

### PR DESCRIPTION
**Pull request by iamfj**
## What does this PR do?

Fixes the v2026.4.x regression reported in #121 by restoring the documented filter flags on `issues list` and bringing back `issues search <query>` as the explicit full-text search entry point.

Both commands now share the same filter parsing, validation, and ID-resolution path, so human-friendly filter values are resolved before the service layer and invalid combinations fail before any API call. `issues list --query <query>` stays available as a deprecated compatibility path for one release window while callers migrate to `issues search <query>`.

Closes #121

## Type of change

- [x] Bug fix
- [x] New feature
- [ ] Refactor (no behavior change)
- [x] Documentation
- [x] Tests
- [ ] Build / CI

## Checklist

- [x] `npm run check:ci` passes (lint + format)
- [x] `npx tsc --noEmit` passes (type check)
- [x] `npm test` passes (unit tests)
- [x] New code has tests (happy path + primary error case)
- [x] Commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)

## Testing

Verified in this branch with:

```bash
npm run check:ci
npx tsc --noEmit
npm test
```

`npm test` currently passes with 36 test files / 362 tests.

Manual verification against a real Linear workspace:

```bash
npm run build

node dist/main.js issues list --team ENG --status "Todo,In Progress" -l 5
node dist/main.js issues list --assignee me --priority 1 -l 5
node dist/main.js issues search "authentication bug" --team ENG --label "Bug" -l 5
node dist/main.js issues list --query "authentication bug" --team ENG -l 5
```

Validation should fail before any API call for bad flag combinations or malformed values, for example:

```bash
node dist/main.js issues list --status "Todo"
node dist/main.js issues list --priority 9
node dist/main.js issues list --due-after 2026-12-31 --due-before 2026-01-01
```

## Notes for reviewers

- `src/common/resolve-filters.ts` centralizes filter parsing, dependency checks, date validation, and resolver calls so commands stay thin and services continue to accept UUIDs only.
- Filtered `issues list` uses `FilteredSearchIssuesDocument` because the existing `GetIssuesDocument` does not accept a caller-provided `IssueFilter`. The service still wraps filtered list queries with the existing non-completed constraint, so `list` keeps its current "active issues" semantics.
- `issues list --query` is intentionally still wired to `searchIssues` as a deprecated compatibility path. Docs and help text now point users to `issues search <query>`.
- This PR does **not** change the paginated `{ nodes, pageInfo }` response shape introduced in v2026.4.x. Scope here is restoring the missing filtering/search CLI surface from #121.

### CODE REVIEW

File: src/commands/issues.ts [hunk 1]
```diff
@@ -178,40 +183,96 @@ async function applyRelation(
...
-          outputSuccess(result);
-        } else {
-          const result = await listIssues(ctx.gql, paginationOptions);
-          outputSuccess(result);
-        }
-      }),
-    );
+  addFilterOptions(
+    issues
+      .command("list")
```
Comment (iamfj) [inline src/commands/issues.ts:223]: I’d consider keeping `--query <text>` here as a deprecated compatibility alias for at least one release. Restoring `issues search <query>` is a good cleanup, but hard-removing the current flag surface in the same PR creates another CLI break for anyone who already adapted to v2026.4.x.

File: src/common/issue-filter.ts [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+  createdBefore?: string;
+  completedAfter?: string;
+  completedBefore?: string;
+  updatedAfter?: string;
+  updatedBefore?: string;
+  hasBlockers?: boolean;
+  isBlocking?: boolean;
+}
+
+export interface RawFilterFlags {
```
Comment (iamfj) [inline src/common/issue-filter.ts:28]: This file is pulling together two different responsibilities right now: command-facing CLI flag parsing/validation (`RawFilterFlags`, dependency rules) and service-facing GraphQL filter construction (`buildIssueFilter`). I think the design would read more cleanly if those concerns were split instead of growing `src/common/` into a broad helper bucket.

File: src/commands/resolve-filters.ts [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+ * @param ctx - Command context with SDK and GraphQL clients
+ * @param opts - Raw filter flags from CLI options
+ * @returns Resolved filter options with UUIDs ready for buildIssueFilter()
+ */
+export async function resolveFilterOptions(
+  ctx: CommandContext,
+  opts: RawFilterFlags,
+): Promise<IssueFilterOptions> {
+  // 1. Format validation
+  for (const value of [
```
Comment (iamfj) [inline src/commands/resolve-filters.ts]: Minor UX nit: this reuses `parseDueDate()` for created/completed/updated filters too, so something like `--created-after foo` will end up reporting an "Invalid due date" error. A generic YYYY-MM-DD validator, or a flag-specific message, would make the error clearer.

**Review by iamfj — COMMENTED** [review]
Nice progress overall. The direction here makes sense: restoring a dedicated `issues search <query>` command is clearer than overloading `list`, sharing the same filter surface between `list` and `search` is a good UX improvement, and the validation flow in `resolveFilterOptions()` is sensible.

A few things I’d still take another pass on:

- I’d strongly consider keeping `issues list --query` as a deprecated compatibility path for at least one release. This PR fixes a regression, but removing the current `--query` entry point at the same time creates another avoidable break for callers that already adapted to v2026.4.x.
- The new filter abstraction could use one more architecture pass. `src/common/issue-filter.ts` currently mixes command-facing flag parsing/validation with service-facing GraphQL filter construction. In a codebase with explicit layers, I think that responsibility split would be clearer if those concerns lived separately.
- The test additions are useful, but the regression in #121 happened in command wiring. I’d feel better with command-level coverage for `issues list` / `issues search` with filters so the actual CLI path is locked down.
- One docs follow-up: `CHANGELOG.md` still says the search subcommands were merged into `list`. After this PR that statement becomes stale again, so it would be good to update that at the same time.

Overall: good fix direction, just a few places where I think a bit more polish would make this much safer to merge.

File: src/commands/resolve-filters.ts (hunk 3 above)
Comment (iamfj) [reply src/commands/resolve-filters.ts]: Fixed earlier on this branch in `85c558b`: `resolveFilterOptions()` now validates each date flag individually and raises a flag-specific `must be a valid date in YYYY-MM-DD format` error instead of surfacing `parseDueDate()`'s due-date wording.

File: src/commands/issues.ts (hunk 1 above)
Comment (iamfj) [reply src/commands/issues.ts:223]: Kept `issues list --query` as a deprecated compatibility path for now. `issues list` now routes through `searchIssues()` when `--query` is present, and I added command-level coverage for both `issues search <query>` and the deprecated `list --query` path in `tests/unit/commands/issues.test.ts`.

File: src/common/issue-filter.ts (hunk 2 above)
Comment (iamfj) [reply src/common/issue-filter.ts:28]: Split the responsibilities now: command-facing flag parsing/validation lives in `src/commands/issue-filter.ts`, service-facing GraphQL filter construction lives in `src/services/issue-filter.ts`, and `src/common/issue-filter.ts` only keeps the shared resolved filter shape used across the boundary.
